# Generated by Django 5.0.2 on 2024-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idp_user', '0001_initial_squashed_0005_alter_userrole_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.CharField(help_text='The name of the organization the user role belongs to, if any.',
                                   max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='app_entities_restrictions',
            field=models.JSONField(
                help_text='This dictionary contains explicit restrictions about the app entities that the user can access, in the form: {<entity_type>: [1, 2]}',
                null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='permission_restrictions',
            field=models.JSONField(default=dict,
                                   help_text="This dictionary contains explicit restrictions regarding app permissions, in the form: {'perform_operation_1': {'entity_type': [1, 2]}, 'perform_operation_2': false}"),
        ),
    ]
