name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_repository:
        description: 'Target repository'
        required: true
        default: 'godd0t/docs'

permissions:
  contents: write

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,drf,async]
      - name: Lint with black and ruff
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test

  deploy-docs:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.target_repository }}
          token: ${{ secrets.PAT_TOKEN }} # Replace with the actual name of your secret containing the PAT

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install -e .[docs]

      - run: mkdocs gh-deploy --force

      - name: Create dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }} # Replace with the actual name of your secret containing the PAT
          repository: django-idp-user
          event-type: deployment-complete
